# https://github.com/compose-spec/compose-spec/blob/master/spec.md
# https://github.com/docker/awesome-compose/blob/master/official-documentation-samples/wordpress/README.md

services:
    mariadb:
        build:
            context: ./requirements/mariadb
            # dockerfile: Dockerfile # 파일명이 Dockerfile이 아니면 명시해줘야 함
        container_name: mariadb
        restart: on-failure
        env_file: .env
        # .env 파일에 정의된 것 외에 추가 환경 변수를 추가
        environment:
            - MYSQL_DATABASE=$MYSQL_DATABASE
        # dbdata라는 명명된 볼륨을 /var/lib/mysql 디렉토리에 마운트
        ports:
            - "3306"
        volumes:
            - dbdata:/var/lib/mysql
        # 이미지에 대한 기본 CMD 지침을 재정의
        # command: "--default-authentication-plugin=mysql_native_password"
        networks:
            - app-network
    wordpress:
        depends_on:
            - mariadb
        build:
            context: ./requirements/wordpress
        container_name: wordpress
        restart: on-failure
        env_file: .env
        environment:
            - WORDPRESS_DB_HOST=mariadb:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=$MYSQL_DATABASE
        ports:
            - "9000"
        volumes:
            - wordpress:/var/www/html
        networks:
            - app-network
    webserver:
        depends_on:
            - wordpress
        build:
            context: ./requirements/nginx
        container_name: webserver
        restart: on-failure
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - app-network

volumes:
    wordpress:
    dbdata:

networks:
    app-network:
        driver: bridge
